version: 2
jobs:
  kinetic:
    docker:
      - image: ros:kinetic

    working_directory: ~/eagleye

    steps:
      - checkout

      - run:
          name: Install rtklib_msgs
          command: |
            git clone https://github.com/MapIV/rtklib_ros_bridge.git

      - run:
          name: Install catkin
          command: |
            apt-get update -qq && apt-get install -y python-catkin-tools
            source /opt/ros/kinetic/setup.bash
            rosdep install --from-paths . --ignore-src -y --rosdistro kinetic

      - run:
          name: Install ros-kinetic-can-msgs
          command: |
            apt-get install ros-kinetic-can-msgs

      - run:
          name: Install ros-kinetic-geodesy
          command: |
            apt-get install ros-kinetic-geodesy

      - run:
          name: Build
          command: |
            source /opt/ros/kinetic/setup.bash
            mkdir -p /tmp/ws/src
            ln -s `pwd` /tmp/ws/src/package
            cd /tmp/ws/src
            catkin_init_workspace
            cd ../
            catkin_make -DCMAKE_BUILD_TYPE=Release -j1
  melodic:
    docker:
      - image: ros:melodic

    working_directory: ~/eagleye

    steps:
      - checkout

      - run:
          name: Install rtklib_msgs
          command: |
            git clone https://github.com/MapIV/rtklib_ros_bridge.git

      - run:
          name: Install catkin
          command: |
            apt-get update -qq && apt-get install -y python-catkin-tools
            source /opt/ros/melodic/setup.bash
            rosdep install --from-paths . --ignore-src -y --rosdistro melodic

      - run:
          name: Install ros-melodic-geodesy
          command: |
            apt-get install ros-melodic-geodesy

      - run:
          name: Build
          command: |
            source /opt/ros/melodic/setup.bash
            mkdir -p /tmp/ws/src
            ln -s `pwd` /tmp/ws/src/package
            cd /tmp/ws/src
            catkin_init_workspace
            cd ../
            catkin_make -DCMAKE_BUILD_TYPE=Release -j1

workflows:
  version: 2
  ros_build:
    jobs:
      - kinetic
      - melodic
