ref_index:
  time_unit: 0 # 0:[s], 1:[ns]
  time: 2
  x: 4
  y: 5
  z: 6
  ori_x: 7
  ori_y: 8
  ori_z: 9
  ori_w: 10

data_index:
  time_unit: 0 # 0:[s], 1:[ns]
  time: 2
  x: 4
  y: 5
  z: 6
  ori_x: 7
  ori_y: 8
  ori_z: 9
  ori_w: 10

eagleye_log:
  tf_num: 0 # 0:plane, 1:mgrs
  time_unit: 0 # 0:[s], 1:[ns]