ref_index:
  separate_time_stamp: False #[True]:Set time_sec and time_nsec / [False]:Set time
  time_unit: 1 # 0:[s], 1:[ns]
  use_quaternion: True # [True]:Set Quaternion / [False]:Set Euler
  use_radian: True # [True]:radian / [False]:degree
  use_vel: False #
  use_angular: False #
  time_sec: 1
  time_nsec: 2
  time: 2
  x: 4
  y: 5
  z: 6
  ori_x: 7
  ori_y: 8
  ori_z: 9
  ori_w: 10
  roll: 7
  pitch: 8
  yaw: 9
  vel_x: 0
  vel_y: 0
  vel_z: 0
  angular_x: 0
  angular_y: 0
  angular_z: 0

data_index:
  separate_time_stamp: False #[True]:Set time_sec and time_nsec / [False]:Set time
  time_unit: 0 # 0:[s], 1:[ns]
  use_quaternion: True # [True]:Set Quaternion / [False]:Set Euler
  use_radian: True # [True]:radian / [False]:degree
  time_sec: 1
  time_nsec: 2
  time: 2
  x: 4
  y: 5
  z: 6
  ori_x: 7
  ori_y: 8
  ori_z: 9
  ori_w: 10
  roll: 7
  pitch: 8
  yaw: 9

twist_index:
  time_unit: 0 # 0:[s], 1:[ns]
  time: 2
  linear_x: 4
  linear_y: 5
  linear_z: 6
  angular_x: 7
  angular_y: 8
  angular_z: 9

eagleye_log:
  tf_num: 0 # 0:plane, 1:mgrs
  time_unit: 1 # 0:[s], 1:[ns]

param:
  reverse_imu_flag: False
  plane_num: 7 # Plane Cartesian coordinate system number (default:7 = 7)
  sync_threshold_time_data_param: 0.01 # Time threshold for judgment at synchronized. (default:0.01 = 0.01[s])
  leap_time_param: 0.0 # Offset correction for time synchronization. (default:0.0 = 0.0[s])
  tf_x_param: 0.0
  tf_y_param: 0.0
  tf_across_param: 0.0
  tf_along_param: 0.0
  tf_height_param: 0.0
  tf_yaw_param: 0.0
  distance_length_param: 100 # Distance to calculate relative trajectory. (default:100 = 100[m])
  distance_step_param: 50 # Calculate relative trajectories step (default:50 = 50[m])
  ref_data_name_param: 'ref data' # Reference Legend Name. (default:'ref data')
  eval_step_max_param: 3.0 # Maximum value of error to be evaluated default (default:3.0 = 3.0[m])