name: docs

on:
  push:
    branches:
      - develop-ros2
      - main-ros2

jobs:
  doxygen:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Generate API docs
        run: doxygen Doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/develop-ros2'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/api/html
